{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mbelling",
    "module": "rpi-ws281x-java",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rpi-ws281x-java-2.0.0-SNAPSHOT.jar",
          "url": "rpi-ws281x-java-2.0.0-SNAPSHOT.jar",
          "size": 56170,
          "sha512": "9b5a20bb82caf4bc9460cc11ff112242f6a8d8c0ca00cc3dd5ca43a20f612750dda1e1d8eb835ce44b4e75e44e012797a3c1adf3791d9d099f095b10f7ebfc54",
          "sha256": "41413000089beb2a539e87051f5191b953ff14c93d5fd36571265793c60ad009",
          "sha1": "d081c1bb1d6b7e75a2fd7a4cad7d69216a1a0bc3",
          "md5": "3e45d33c980ba12b635b075244792382"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "rpi-ws281x-java-2.0.0-SNAPSHOT.jar",
          "url": "rpi-ws281x-java-2.0.0-SNAPSHOT.jar",
          "size": 56170,
          "sha512": "9b5a20bb82caf4bc9460cc11ff112242f6a8d8c0ca00cc3dd5ca43a20f612750dda1e1d8eb835ce44b4e75e44e012797a3c1adf3791d9d099f095b10f7ebfc54",
          "sha256": "41413000089beb2a539e87051f5191b953ff14c93d5fd36571265793c60ad009",
          "sha1": "d081c1bb1d6b7e75a2fd7a4cad7d69216a1a0bc3",
          "md5": "3e45d33c980ba12b635b075244792382"
        }
      ]
    }
  ]
}
