# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
env:
  MAVEN_CLI_OPTS: >-
    --file connectncharge/pom.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package $MAVEN_CLI_OPTS
    - name: Generate Project Pages
      run: mvn site $MAVEN_CLI_OPTS
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.9.0
      with:
        # The directory for storing badges, relative to the root of the repository.
        badges-directory: connectncharge/target/site
        jacoco-csv-file: connectncharge/target/site/jacoco/jacoco.csv
 
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        # Artifact name
        name: connectncharge-project-pages
        # Path of the directory containing the static assets.
        path: connectncharge/target/site
        # Duration after which artifact will expire in days.
        #retention-days: # optional, default is 1
        
        
   # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1 # or the latest "vX.X.X" version tag for this action
        with:
          artifact_name: connectncharge-project-pages
  
  # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  #- name: Update dependency graph
  #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
